### ISSUE TITLE
Can you post to nuget?

### ISSUE THREAD

**Issue by katlimruiz** [RickStrahl/json.date-extensions#7]
It would be great if this get posted to nuget.org to maintain it up-to-date without doing it manually.

I see you are using VS 2012, so it should be natural to post to nuget :+1:

I think this is a great library and should be incorporated to the standard! With angularjs and so many frameworks for javascript it makes a lot of sense to have Date objects when parsing the fields.

**Comment by RickStrahl** [comment]
I'm definitely going to push it to NuGet. NuGet will be phasing out support for client side content and in future versions of Visual Studio NPM/JSPM should be used for that. So if it gets packaged that's where it will go. 

I'll look into it...

**Comment by RickStrahl** [comment]
There's now a Bower package.

      > Bower install json.data-extensions
